# Level 2 - Task 3: Feature Engineering

## Objective
Perform feature engineering on the Zomato restaurant dataset by creating
new meaningful features from existing columns.

### Tasks
- Extract restaurant name length
- Extract address length
- Encode table booking availability
- Encode online delivery availability
- Create additional useful numerical features
- Save the feature-engineered dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Outputs/zomato_cleaned.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (9551, 21)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [3]:
required_columns = [
    "Restaurant Name",
    "Address",
    "Has Table booking",
    "Has Online delivery"
]

missing_columns = [col for col in required_columns if col not in df.columns]

if missing_columns:
    print("Missing columns:", missing_columns)
else:
    print("All required columns are available.")

All required columns are available.

 # Restaurant Name Length

In [4]:
df["Restaurant Name Length"] = (
    df["Restaurant Name"]
    .fillna("")
    .astype(str)
    .str.len()
)

print("Restaurant Name Length created successfully.")
df[["Restaurant Name", "Restaurant Name Length"]].head()

Restaurant Name Length created successfully.

          Restaurant Name  Restaurant Name Length
0        Le Petit Souffle                      16
1        Izakaya Kikufuji                      16
2  Heat - Edsa Shangri-La                      22
3                    Ooma                       4
4             Sambo Kojin                      11

 # Address Length

In [5]:
df["Address Length"] = (
    df["Address"]
    .fillna("")
    .astype(str)
    .str.len()
)

print("Address Length created successfully.")
df[["Address", "Address Length"]].head()

Address Length created successfully.

                                             Address  Address Length
0  Third Floor, Century City Mall, Kalayaan Avenu...              71
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...              67
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...              56
3  Third Floor, Mega Fashion Hall, SM Megamall, O...              70
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...              64

 # Encode Table Booking

In [6]:
df["Has Table Booking Encoded"] = (
    df["Has Table booking"]
    .map({"Yes": 1, "No": 0})
)

print("Table Booking encoding:")
print(df["Has Table Booking Encoded"].value_counts(dropna=False))

Table Booking encoding:
Has Table Booking Encoded
0    8393
1    1158
Name: count, dtype: int64

 # Encode Online Delivery

In [7]:
df["Has Online Delivery Encoded"] = (
    df["Has Online delivery"]
    .map({"Yes": 1, "No": 0})
)

print("Online Delivery encoding:")
print(df["Has Online Delivery Encoded"].value_counts(dropna=False))

Online Delivery encoding:
Has Online Delivery Encoded
0    7100
1    2451
Name: count, dtype: int64

# Create Price Range Feature

In [8]:
if "Price range" in df.columns:
    df["Price Range Category"] = df["Price range"].map({
        1: "Low",
        2: "Medium",
        3: "High",
        4: "Very High"
    })

print(df[["Price range", "Price Range Category"]].head())

   Price range Price Range Category
0            3                 High
1            3                 High
2            4            Very High
3            4            Very High
4            4            Very High

# Create Votes Log Feature

In [9]:
if "Votes" in df.columns:
    df["Log Votes"] = np.log1p(df["Votes"])

print(df[["Votes", "Log Votes"]].head())

   Votes  Log Votes
0    314   5.752573
1    591   6.383507
2    270   5.602119
3    365   5.902633
4    229   5.438079

# Check Engineered Features

In [10]:
engineered_features = [
    "Restaurant Name Length",
    "Address Length",
    "Has Table Booking Encoded",
    "Has Online Delivery Encoded",
    "Price Range Category",
    "Log Votes"
]

available_features = [
    col for col in engineered_features
    if col in df.columns
]

print("Engineered Features:")
print(available_features)

df[available_features].head(10)

Engineered Features:
['Restaurant Name Length', 'Address Length', 'Has Table Booking Encoded', 'Has Online Delivery Encoded', 'Price Range Category', 'Log Votes']

,Restaurant Name Length,Address Length,Has Table Booking Encoded,Has Online Delivery Encoded,Price Range Category,Log Votes
0,16,71,1,0,High,5.752573
1,16,67,1,0,High,6.383507
2,22,56,1,0,Very High,5.602119
3,4,70,0,0,Very High,5.902633
4,11,64,1,0,Very High,5.438079
5,12,71,0,0,High,5.820083
6,10,83,1,0,Very High,6.255750
7,7,81,1,0,Very High,6.519147
8,40,69,1,0,Very High,6.432940
9,8,67,1,0,High,6.278521

# Dataset Information

In [11]:
print("Final Dataset Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df[available_features].isnull().sum())

Final Dataset Shape: (9551, 27)

Data Types:
Restaurant ID                    int64
Restaurant Name                    str
Country Code                     int64
City                               str
Address                            str
Locality                           str
Locality Verbose                   str
Longitude                      float64
Latitude                       float64
Cuisines                           str
Average Cost for two             int64
Currency                           str
Has Table booking                  str
Has Online delivery                str
Is delivering now                  str
Switch to order menu               str
Price range                      int64
Aggregate rating               float64
Rating color                       str
Rating text                        str
Votes                            int64
Restaurant Name Length           int64
Address Length                   int64
Has Table Booking Encoded        int64
Has Online Delivery Encoded      int64
Price Range Category               str
Log Votes                      float64
dtype: object

Missing Values:
Restaurant Name Length         0
Address Length                 0
Has Table Booking Encoded      0
Has Online Delivery Encoded    0
Price Range Category           0
Log Votes                      0
dtype: int64

# Feature-Engineered Dataset

In [12]:
output_path = "../Outputs/feature_engineered_zomato.csv"

df.to_csv(output_path, index=False)

print(f"Feature-engineered dataset saved to: {output_path}")

Feature-engineered dataset saved to: ../Outputs/feature_engineered_zomato.csv

In [13]:
df_check = pd.read_csv("../Outputs/feature_engineered_zomato.csv")

print("Saved Dataset Shape:", df_check.shape)

print("\nNew Features:")
print([
    col for col in df_check.columns
    if col in engineered_features
])

df_check.head()

Saved Dataset Shape: (9551, 27)

New Features:
['Restaurant Name Length', 'Address Length', 'Has Table Booking Encoded', 'Has Online Delivery Encoded', 'Price Range Category', 'Log Votes']

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Aggregate rating,Rating color,Rating text,Votes,Restaurant Name Length,Address Length,Has Table Booking Encoded,Has Online Delivery Encoded,Price Range Category,Log Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,4.8,Dark Green,Excellent,314,16,71,1,0,High,5.752573
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,4.5,Dark Green,Excellent,591,16,67,1,0,High,6.383507
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,4.4,Green,Very Good,270,22,56,1,0,Very High,5.602119
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,4.9,Dark Green,Excellent,365,4,70,0,0,Very High,5.902633
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,4.8,Dark Green,Excellent,229,11,64,1,0,Very High,5.438079